# -*- coding: utf-8 -*-
"""
Created on Wed Dec 14 12:19:38 2016

@author: Libby
"""

q1 = "APERITIF GLORY GREEN BLUE AMBER PARC FACADE CROUTON SCOT GREEN DOG GALOP NAIVE RED DELL LEE YOUTH PURPLE COLUMN LADY ESTATE ORANGE JARDINIERE ALICE BEE WALTZ YELLOW PATCH HOLE SPY DREAM KEPI FROG DELICIOUS RUSSET SHAMBLE WORM WIND FORM KEATS LIMBO MIRROR ORE GNAT PATRON REICH VICUNA CERISE THIRTEEN TUTOR NIGHT DOPPELGANGER RIVER GREY IMPERIAL".split()

q2 = "A ABANDON ABATTOIR ADAMS ALDRIN ANTISEPTIC APART ART AUTUMN BLIND CANOPUS CARD CHIN DAYS EAST EONS EROTIC GAVE HELIUM I INTERSEPTAL LARGE LEO LINUS LITTLE MEN MICE MONACO MY NAP NAPE OLE PARIS PENNSYLVANIA PIGS NOTABLE POLE QUEEN RAPHAEL REE REMOVE RIDGE SEPTEMBER SLAIN TEMPERANCE THYMINE TOME TOWERING TRANSEPT TRICK TRUELOVE ULSTER VESTA WEEK WISE".split()

q4 = ["FDWBKRHQIRELAND","TIVUCPENCE","SIBUHEW"]

q8 = ["IDYHHTS","DTDWEOS","EHAORRC"]

q13 = ["SEAHORSE GOOSE WOLF CAT PIG EAGLE OWL MOLE FINCH SHEEP BEAR FROG".split(),
       "TNF PLT PREFF OTAE OMWF SMV SFWFN FMURP NMNF PFN FIFWFN PLFIWF".split(),
       "SYS RAE TDE BSI RAM UMW ATN GSS UIN IRW OHS UCH".split(),
       "FORGET CHURCH UNPACK SCENIC BARTON PATCHY JUBHAH STREAM CLOSER QUOTES LIKELY CHERRY".split(),
       "BRA HFR HHMSB BDDX LYYM FFR ACJGV PPFNN SUJG NPX EMIIPC JXTFLH".split(),
       "SFN GOD HUUHP IQFI WYMJ LOL AOVMU WDMUJ NAKD DGR TNSJPL DIMEUF".split(),
       "IY OW AU WS DO NE FT HE AE WT EA RD".split(),
       "UBCZYYMW LOXBXJFQ ZQKNNRS ZGQTNJD XIXDHBJPF TGMGYFMU GCAFMPBW FZDXRC YBQSPDCHB KQOKKJMKE JOJQCRYTQGJ KSWQKQVPJX".split()]

q13ams = "one two three four five six seven eight nine ten eleven twelve".split()
q13pms = "thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty twentyone twentytwo twentythree twentyfour".split()

q27 = "BZL CTJEZBSZ DZRBTDFBS DZRBTDFBSA DZSDAB DZSDAB EBAACK EBZCKZS FVAS GAAMQ GAF GAHFSAK GTFS GTOBZ HMSNCBMS JDFBRTF JDFBRTFS JDUFBRTFAS JEFBRTFSAS JEXKKAS JKAASOFE JKASOFDEAS JKTAB JZNTKKZBTMJ JZNTKKZTBA KPTGGTSNZBSZ KQAAGTSNAS KZMBAZM KZMBMJ LZZNI NALAZMV NALTST OAGTAB OFFNJDUMKKAB OZGZSDA PABJAZM PTABNA PTBNF PTJJAS PZIMBAS PZKKMLZSSAS PZNAS QAANJDUZZG QZKABLZS RFTJJFSJ RTJDAJ ZBTAJ ZWMZBTMJ".split()


q33 = """Rpgqty waqs tsc Qfgwejf
Wjq j dgbby, sjkky jbb qgub
Wats j hgpfhgo kakc gr jfn j outtgf fgqc
Jfn twg cycq ejnc gut gr hgjb ygu

Rpgqty j tsc Qfgwejf
Aq j rjapy tjbc, tscy qjy vcpy
Sc wjq ecppy ejnc gr qfgw out tsc hsabnpcf lfgw
Hspaqtejq Sgw sc hjec tg barc gfc njy"""

#          abcdefghijklmnopqrstuvwxyz
q33alph = "ilejmnoc.apk.dbrsfhtuvw.y."
